### ISSUE TITLE
Calculate bitangents (binormals?)

### ISSUE THREAD

**Issue by sercero** [OGRECave/blender2ogre#101]
Hello @paroj,

I have recently been delving into shaders and was having trouble when using the `binormal` from Ogre (I assume it is the same as bitangent, right?).

I thought it was being calculated by Ogre, but now I think that it should be in the mesh buffer...

So I was thinking of implementing the exporting of bitangents/binormals from blender since I saw it was in `ogremeshxml.dtd`.

What I wonder before going into that trouble if it is worth it, is it better to calculate it in the vertex shader or to have it as information in the mesh?
 
What made me stop is this sentence from the Blender manual: _"Bitangent vector of this vertex for this polygon (must be computed beforehand using calc_tangents, use it only if really needed, slower access than bitangent_sign)"_.
[MeshLoop(bpy_struct)](https://docs.blender.org/api/2.79/bpy.types.MeshLoop.html#bpy.types.MeshLoop)

**Comment by paroj** [comment]
bitangent and binormal is the same and defined as `B = cross(normal, tangent)`, so passing it as an attribute is redundant. Therefore passing it as an attribute is not worth it (probably the existance of such attribute is just some fixed function legacy).

However note, that the tangents [generated by Ogre](https://ogrecave.github.io/ogre/api/latest/class_ogre_1_1_tangent_space_calc.html) might not match what you normal-map expects, as Ogre does not yet follow http://www.mikktspace.com/ which is de-facto a standard now and used by e.g. blender.

**Comment by sercero** [comment]
I was thinking that you could spare the calculation in the shader by passing it as an attribute and in fact this is what I tried to do the first time I was dealing with normal maps when I saw in the manual that Ogre was passing such an attribute.

So the calculation can be done offline from Blender and then passed as an attribute to the shader to avoid the cross product wich is a somethat expensive calculation, I think.

Anyway it was easy to do so I already implemented it and tested it with the shader code that I left commented some time ago that now it works because now Ogre is passing the binormal to the shader.

The disadvantage I see here is that it might be unwise to write a shader that expects the binormal to be already precalculated because it seems to be something that is not very common.

**Comment by paroj** [comment]
> I was thinking that you could spare the calculation in the shader by passing it as an attribute 

the cost of storing another vec3 per vertex by far exceeds that one cross-product. Especially when you factor in the actual normal map lighting calculation that comes after. Thats why nobody is actually doing this.
