### ISSUE TITLE
Exporter duplicates mesh?

### ISSUE THREAD

**Issue by Quintus** [OGRECave/blender2ogre#102]
Hi all,

okay, I first off admit I am a newbie in the area. I've been fiddling with Blender since a few days only and with Ogre not much longer. Still, the effect I see is puzzling. Attached you find an entirely simple model that uses Blender's built-in monkey face (Suzanne) along with a plane a cone. If I export this with File -> Export -> Ogre3D this exports fine, but within Blender Suzanne and the plane below it appear to have been duplicated. You can try by moving the face off its initial position. A copy remains in place that hasn't been there before the export.

I'm using blender2ogre 0.8.1 with Blender 2.92.0 on Debian 10.

The effect is a nuisance mostly, since I can just close and reopen Blender and everything is as it has been before, but I don't understand why this is happening. Again, the exported `.mesh`model is fine, the issue is about the state Blender is in after the export.

Here's the console output:

~~~~~
Read prefs: /home/quintus/.config/blender/2.92/config/userpref.blend
/run/runtime/quintus/gvfs/ non-existent directory
[ INFO] Starting io_ogre (0, 8, 1)
Read blend: /home/quintus/repos/rpg-rawdata/blends/suzanne.blend
[DEBUG] Context.blend_data: /home/quintus/repos/rpg-rawdata/blends/suzanne.blend
[DEBUG] Context.scene.name: Scene
[DEBUG] Self.filepath: /tmp/export2/suzanne.blend
[DEBUG] Self.last_export_path: None
[DEBUG] Self.filepath: /tmp/export2/suzanne.blend
________________________________________________________________________________
[ INFO] Target_path: /tmp/export2
[ INFO] Target_file_name: suzanne.blend
[DEBUG] Target_file_name_no_ext: suzanne
[ INFO] * Processing Scene: suzanne, path: /tmp/export2
[DEBUG] ABABA Suzanne
[DEBUG] ABABA Plane
[DEBUG] ABABA Cone
[ INFO] + Merge Group: merge.testmesh
[ INFO]   - Suzanne.001
[ INFO]   - Plane.001
[ INFO]   - Cone.001
[ INFO] * Processing Materials
[WARNING] No materials, not writting .material script
[ INFO] * Exporting root node: testmesh 
[ INFO] Vertices: 544
[ INFO] Loop triangles: 1032
[ INFO] * Generating: testmesh.mesh.xml
[ INFO] * Writing shared geometry
 + Faces [==================================================>] 100.0%   
[ INFO] - Done at 0.17 seconds
[ INFO] * Writing submeshes
[ INFO] - Done at 0.18 seconds
[ INFO] - Created testmesh.mesh.xml at 0.18 seconds
[ INFO] Removing generated xml file after conversion: /tmp/export2/testmesh.mesh.xml
[ INFO] - Created testmesh.mesh in total time 0.31 seconds
[ INFO] Extern material: _missing_material_
________________________________________________________________________________
Report:
  Original Vertices: 544
  Exported Vertices: 3018
  Original Faces: 1032
  Exported Triangles: 1032
  MESHES: 1

Extended Report:
  MESHES:
    . testmesh
________________________________________________________________________________
Saved session recovery to '/tmp/quit.blend'
[ INFO] Unloading io_ogre (0, 8, 1)

Blender quit
~~~~~

[suzanne.zip](https://github.com/OGRECave/blender2ogre/files/6506474/suzanne.zip)

**Comment by paroj** [comment]
the exporter duplicates the meshes to add & apply the modifiers (e.g. triangulation). Seems that we dont clean up properly after that.

**Comment by sercero** [comment]
I have probably introduced a bug there, let me check it out.

**Comment by sercero** [comment]
Well, the bad news is that it seems this bug was even in version 0.8.0 so it came with the initial Blender 2.8+ support.

So I have no reference for fixing it, save comparing the code to the 2.7x version, so it will be more difficult.

The good news is that it wasn't me who broke it 😅

**Comment by sercero** [comment]
@Quintus this issue should be fixed in master by now, please let us know.

**Comment by Quintus** [comment]
I can confirm that the issue is resolved with current master. No duplicates happen anymore.

Thanks for the quick fix!
