### ISSUE TITLE
Cannot enable Exporter

### ISSUE THREAD

**Issue by disloyalpick** [OGRECave/blender2ogre#106]
![oave4Ij 1](https://user-images.githubusercontent.com/13305403/120647966-28bc0700-c449-11eb-97f1-0508c7bd99ec.png)
The importer works just fine. But the exporter is throwing an error. Does anyone know what I can do to fix it?

**Comment by sercero** [comment]
Hello @disloyalpick what version of the exporter are you using (master branch or 2.7x-support branch)?

Another thing, what do you mean by the importer? This proyect does not have importing (yet).

**Comment by disloyalpick** [comment]
its the 2.7 branch and my bad  thought the importer was bundled with the exporter

**Comment by sercero** [comment]
Can you show the full log from the CLI?

Also a sample .blend file to see how to reproduce this.

The only thing I can think of is that you are using Blender 2.79a.

Is there a reason why you are not using Blender 2.79b, I always test with that version which is the last of the 2.7x series.

**Comment by disloyalpick** [comment]
Oof it is 2.79a, and I never realized it. :(

**Comment by sercero** [comment]
Anyway, I just downloaded Blender 2.79a and used it with the 2.7x-support branch and it works.

It seems you are using windows, enable the console (Window -> Toggle System Console) and paste the log output from there because I want to see if there is more context to the errror.

Another thing: how did you install the add-on?

**Comment by disloyalpick** [comment]
I followed the installation by putting the io_ogre folder into the
scripts/addons directory.

**Comment by disloyalpick** [comment]
`Read prefs: C:\Users\dislo\AppData\Roaming\Blender Foundation\Blender\2.79\config\userpref.blend
found bundled python: C:\Program Files\Blender Foundation\Blender\2.79\python
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\dislo\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\api.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\dislo\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\config.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\dislo\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\console.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\dislo\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\game_logic.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\dislo\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\meshy.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\dislo\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\ogre\\__init__.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\dislo\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\properties.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\dislo\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\report.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\dislo\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\rhino3dm\\__init__.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\dislo\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\shader.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\dislo\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\terrain.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\dislo\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\todo.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\dislo\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\ui\\__init__.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\dislo\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\unused.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\dislo\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\util.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\dislo\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\xml.py'
Exception while reading windows registry: [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\modules\addon_utils.py", line 331, in enable
    mod = __import__(module_name)
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\io_ogre\__init__.py", line 46, in <module>
    from . import ui
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\io_ogre\ui\__init__.py", line 25, in <module>
    from . import export
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\io_ogre\ui\export.py", line 25, in <module>
    from ..ogre import mesh
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\io_ogre\ogre\mesh.py", line 6, in <module>
    from ..xml import *
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\io_ogre\xml.py", line 1, in <module>
    from xml.sax.saxutils import XMLGenerator, quoteattr
  File "C:\Users\dislo\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\xml.py", line 1, in <module>
    from xml.sax.saxutils import XMLGenerator, quoteattr
ImportError: No module named 'xml.sax'; 'xml' is not a package

`

**Comment by sercero** [comment]
It seems that you have copied the *contents* of the io_ogre folder into the addons directory? 
Is that right?

You have to copy the io_ogre folder into the addons directory, check that there are other folders called io_*.

If you copied the contents of the folder you have to hunt down the files and delete them, or you could reinstall Blender.

**Comment by disloyalpick** [comment]
i did that. i even downloaded a fresh zip of blender.

**Comment by paroj** [comment]
the issue seems to be that we ship a file called xml.py:
https://stackoverflow.com/questions/33633954/python-error-importerror-no-module-named-xml-etree/33634074#33634074

the question is though, why is nobody else affected? Maybe you copied that xml.py to the wrong place?

**Comment by disloyalpick** [comment]
i put the io_ogre file in the scripts\addons 

https://i.imgur.com/zJuxkOS.png
https://i.imgur.com/mCqkijQ.png

**Comment by disloyalpick** [comment]
here is the cli output 

'Read prefs: C:\Users\dislo\AppData\Roaming\Blender Foundation\Blender\2.79\config\userpref.blend
found bundled python: C:\Users\dislo\Desktop\blender-2.79b-windows32\2.79\python
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\dislo\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\api.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\dislo\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\config.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\dislo\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\console.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\dislo\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\game_logic.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\dislo\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\meshy.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\dislo\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\properties.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\dislo\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\report.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\dislo\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\rhino3dm\\__init__.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\dislo\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\shader.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\dislo\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\terrain.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\dislo\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\todo.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\dislo\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\ui\\__init__.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\dislo\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\unused.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\dislo\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\util.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\dislo\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\xml.py'
Exception while reading windows registry: [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "C:\Users\dislo\Desktop\blender-2.79b-windows32\2.79\scripts\modules\addon_utils.py", line 331, in enable
    mod = __import__(module_name)
  File "C:\Users\dislo\Desktop\blender-2.79b-windows32\2.79\scripts\addons\io_ogre\__init__.py", line 46, in <module>
    from . import ui
  File "C:\Users\dislo\Desktop\blender-2.79b-windows32\2.79\scripts\addons\io_ogre\ui\__init__.py", line 25, in <module>
    from . import export
  File "C:\Users\dislo\Desktop\blender-2.79b-windows32\2.79\scripts\addons\io_ogre\ui\export.py", line 25, in <module>
    from ..ogre import mesh
  File "C:\Users\dislo\Desktop\blender-2.79b-windows32\2.79\scripts\addons\io_ogre\ogre\mesh.py", line 6, in <module>
    from ..xml import *
ImportError: No module named 'io_ogre.xml'`

**Comment by sercero** [comment]
Can you give us the output of:
`dir C:\Users\dislo\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons`

**Comment by disloyalpick** [comment]
i am actually not sure why there is a macosx folder in there since im on windows

![nTt3ILl 1](https://user-images.githubusercontent.com/13305403/120853472-b4b55800-c549-11eb-980f-695c0a84d782.png)

**Comment by sercero** [comment]
That look very wrong, where are all the other Blender add-ons?

I think that the best course of action would be to reinstall Blender also deleting all the user preferences.

Here is how it looks for me:
![addons](https://user-images.githubusercontent.com/5248597/120854591-c26fdb00-c553-11eb-9f64-897982ce157b.PNG)

**Comment by disloyalpick** [comment]
I will do that. There also used to be a zip file i used in the past to install the addon that worked. but i cant find that anywhere lol

**Comment by sercero** [comment]
Just install the add on dropping the io_ogre folder into the Blender addons folder.

I will see if it is possible to make an installer to make things easier for people.

**Comment by disloyalpick** [comment]
It worked after I put the io_ogre folder into a zip and installing it that way. Thank you for all your help, i appreciate it.
