### ISSUE TITLE
Materials and mesh in .scene files

### ISSUE THREAD

**Issue by screwt** [OGRECave/blender2ogre#11]
I used a DotSceneLoader from the Ogre Wiki and i saw that in .scene file, mesh nodes are supposed to contain a materialFile attribute.

https://github.com/screwt/ogre_experiment_2/blob/feature/dotSceneLoader/src/DotSceneLoader.cpp#L687

But i did not found the blender2ogre code where this append.
Also, the .scene i generate to not have this attributes:

https://github.com/screwt/ogre_experiment_2/blob/feature/dotSceneLoader/bin/Data/scene4/test.scene#L3

Could you enlighten me?

**Comment by paroj** [comment]
I am not really familiar with the codebase either, but that attribute is optional:
https://github.com/screwt/ogre_experiment_2/blob/feature/dotSceneLoader/src/DotSceneLoader.cpp#L718

it seems to be a mechanism for overriding the material stored in the mesh file.

Also this DotSceneLoader is more up to date then the wiki version:
https://github.com/OGRECave/ogitor/blob/master/SceneLoader/src/DotSceneLoader.cpp

**Comment by screwt** [comment]
My bad, i havn't notice material informations are part of the mesh file.
