### ISSUE TITLE
Bug with Ogre Next mesh (OgreMeshTools) export & proposed code changes.

### ISSUE THREAD

**Issue by oldmanauz** [OGRECave/blender2ogre#120]
Hi,
I've been going through the source code of the v0.8.2 release to fix a bug exporting a mesh in the Ogre Next format with (OgreMeshTools.exe) in Blender 2.93 and to look at the complexity to add functionality to export material files to Ogre Next format (*.material.json). I have some bugs/questions/suggestions below. I'm happy to work away at them but wanted to touch base with the people maintaining this plugin before getting carried away. Sorry if this isn't the correct place for all this.

1. =BUG= -- FIXED--
There is a bug where OgreMeshTools failes because the exporter passes the argument -None which is unrecognised.
This is cause by io_ogre\util.py - line 306: **cmd.append('-%s' %config.get('MESH_TOOL_EXPORT_VERSION'))**.

**config.get('MESH_TOOL_EXPORT_VERSION')** isn't declared anywhere.
Changing the line to **cmd.append('-%s' %config.get('MESH_TOOL_VERSION'))** fixes the error.
Related to this bug is the option to select V1&V2 mesh in the export dialogue doesn't show up because in io_ogre\ui\export.py, line 95 = **"General" : ["EX_SWAP_AXIS", "EX_V2_MESH_TOOL_EXPORT_VERSION", "EX_XML_DELETE"],** should read: **"General" : ["EX_SWAP_AXIS", "EX_V2_MESH_TOOL_VERSION", "EX_XML_DELETE"],**

2. =QUESTION= --RESOLVED--
Does the tundra related code work? Does it get used by anyone?

3. =QUESTION= --RESOLVED--
io_ogre\config.py - line 176 onwards --> The line "registry_key = winreg.OpenKey(winreg.HKEY_CLASSES_ROOT, r'Software\blender2ogre', 0, winreg.KEY_READ)" always fails and is logged in console because there is no install process to create registry keys. Can this code be removed?

4. =PROPOSAL=--RESOLVED--
The source took a bit of time looking through to get an idea of what is going on. Are making changes like renaming python files to be abit more explicit about their funciton and documenting rough outline of a class' purpose worth making?
Example: Rename material.py to OgreGenerateMaterial.py (Thinking forward to put OgreNext material export code to OgreNextGenerateMaterial.py or something similar)

5. =PROPOSAL= --RESOLVED--
Document in the readme where the settings file is saved: "C:\users\<user>\appdata\roaming\blender foundation\blender\<version>\config\scripts\io_ogre.pickle" I may have missed it but it took a while to find it.

6. =PROPOSAL= --RESOLVED--
Document in the readme the export output filenames.

7. =PROPOSAL= --RESOLVED--
The exporter seems to run fine in 2.93, should this be updated in the source or documented?

8. =QUESTION= --RESOLVED--
What does the code in console.py do?

**Comment by oldmanauz** [comment]
Just been learning how to use GitHub,
For point 1 above, I believe I have made a pull request here: #121

**Comment by paroj** [comment]
> Does the tundra related code work? Does it get used by anyone?

no, tundra is dead. I removed most of it in https://github.com/OGRECave/blender2ogre/commit/66b92d7e3149ca8cf032fc9f0f891113a35904ad

>  What does the code in console.py do?

https://github.com/OGRECave/blender2ogre#console-export

as for the rest: no idea or no strong preference. Some things are already discussed in #121. Also mentioning @sercero for his view.

**Comment by oldmanauz** [comment]
@paroj Just getting my head around GitHub usage. If I want to remove more Tundra related code, should I do it as another commit in the current pull request I have open or is the proper way to create a new fork, with new pull request to keep Issues seperate? Although I have just seen that you have merged that pull request, but for future reference...

**Comment by paroj** [comment]
Ideally you would create one pull-request per issue that you want to fix to allow merging them independently.
The way to organize this is to use multiple branches, each only containing the required commits. You can use the same fork for all of them.

**Comment by oldmanauz** [comment]
@paroj 

Some questions I had after digging around in the code a little:
* Is jMonkey related code still relevant or can it be removed?
* In the "ui/__init__.py" file, it looks like class`OGRE_OP_interface_toggle` tries to create an ogre material editor/viewer. To me it looks like it won't work in 2.9 (maybe 2.8) because of API changes. Is this functionality used and worth some effort to get working again or better to just remove it?
* Is it worth an effort to rename io_ogre instances to io_blender2ogre (or blender2ogre) for consistancies sake?
* Remove ui/helper.py as it is all old information for Blender 2.6 and the readme seems to be the place for up to date information?

**Comment by paroj** [comment]
> Is jMonkey related code still relevant or can it be removed?

it does not seem to do anything more than the current previewer code, so I think it can be removed

> In the "ui/init.py" file, it looks like classOGRE_OP_interface_toggle tries to create an ogre material editor/viewer (ui/material.py functionality). To me it looks like it won't work in 2.9 (maybe 2.8) because of API changes. Is this functionality used and worth some effort to get working again or better to just remove it?

this is a Blender 2.7 relic that can be safely removed.

> Remove ui/helper.py as it is all old information for Blender 2.6 and the readme seems to be the place for up to date information? Also the help menu doesn't display in 2.9 as it currently stands.

this would only be visible with the additional UI mentioned above. Also, the README is indeed a better place. Therefore it can be dropped as well.

> Is it worth an effort to rename io_ogre instances to io_blender2ogre (or blender2ogre) for consistancies sake?

I dont think so
