### ISSUE TITLE
Code base clean up

### ISSUE THREAD

**Issue by oldmanauz** [OGRECave/blender2ogre#125]
@paroj 
Is there benefit to continual code clean up?

What do you/anyone else think about my comments from #124 (below). Does anyone loose any used functionality if the 3 files are removed from the source code? To me, they look like they contain broken or unused code.

If it is chosed to remove them, do you keep a copy of the deleted code in the source somewhere for future reference or are old releases of this plugin a good enough backup?

> This change started to remove a lot of code. I stopped before I got too carried away. It looks to me it looks like there is a lot of code that doesn't work due to API changes or people stopped maintaing it. But I'm not familiar enough with the code or the people using the extra features of the plugin it to make that call.
> 3. Removed code from ui/__init__.py referencing a material viewer (& editor?)
>   - ui/material.py was removed. The code in material.py was moved to unused.py because it looked like someone had spent a lot of time on it and it might be useful for future efforts? I don't know what the correct action to take around this is.
>     Potentially the following files could also be removed. I can't see where this code is currently used.
>     - properties.py
>     - game_logic.py
>     - terrain.py
>

**Comment by sercero** [comment]
Let's not get carried away with the clean up.

It is true that the code is backed up in earlier versions, but in the future people won't even know that it existed in the first place.

I think that there are some valuable things there, perhaps there should be a directory with the older stuff.

**Comment by oldmanauz** [comment]
Its nice to see the material properties plane in the flesh.
My argument for cleaning the code is that as someone new to the code, it took me a while to work out whateverthing is doing. Having extra code in there that doesn't do anything just complicates the process. Can I propose one of the following:
1. Restore `ui/materials.py` and move it along with `game_logic.py`, `unused.py`, `todo.py` and `terrain.py` to a new directory called something like `oldcode` so it is readily availble if someone wants to go looking.
2. Leave all the files in the source. Optionally remove the python 'imports' so the code doesn't rely on them. Comment at the top of each of the source files that they are obselete and unused along with what function they used to serve.

**Comment by sercero** [comment]
OK, it's true that this stuff was removed in 2.8.

It's still in the 2.7x branch so not that big of a loss.

Don't let me get in the way of the fat trimming 😅

**Comment by oldmanauz** [comment]
see #126 for proposed cleanup implementation.
