### ISSUE TITLE
What is a light normal ?

### ISSUE THREAD

**Issue by screwt** [OGRECave/blender2ogre#13]
I read the last changes and now directional lights may have a normal.

https://github.com/OGRECave/blender2ogre/blob/master/io_ogre/ogre/scene.py#L536

https://github.com/OGRECave/DotSceneFormat/blob/master/dotscene.dtd#L31

But what is it suppose to be? the direction? the opposit direction? (of the light)

Thank you for your time.

**Comment by paroj** [comment]
yes, the direction: https://github.com/OGRECave/ogitor/blob/master/SceneLoader/src/DotSceneLoader.cpp#L499

I just kept to the DTD here as most parsers do not know "direction".

I am however in favour of just dropping it as the default direction (0,0,1) gets transformed by the parent scene node anyway:
https://github.com/OGRECave/blender2ogre/blob/master/io_ogre/ogre/scene.py#L382

**Comment by screwt** [comment]
I'm testing ogre 2.1 , it seems like light orientation is not affected by the parent orientation.

**Comment by paroj** [comment]
they should be identical:
https://github.com/OGRECave/ogre/blob/v2-1/OgreMain/src/OgreLight.cpp#L253

**Comment by paroj** [comment]
normal/ direction is gone as lights are oriented with their scene node
