### ISSUE TITLE
Wolverine (Monster Jam (on Rigs of Rods))

### ISSUE THREAD

**Issue by KK-1701-K** [OGRECave/blender2ogre#132]
![Wolverine](https://user-images.githubusercontent.com/96151715/146093164-c89fd316-61eb-4f03-abf2-d215022d3000.png)
Some time ago, I posted a request on https://sim-monsters.com/ for Wolverine, the Marvel Comics Monster Jam truck which won the Monster Jam World Finals 4 Racing Championship, but the site's personnel denied me the truck and instead told me to create it myself. Yet Blender has been of no use to me since the first time I started using it.

Finally, my last straw is gone. The Sim-Monsters personnel refuse to answer my request, lose their weakness, and abide order. That's why I have installed Blender so I may do what they will not, but I will need a complete walkthrough for this huge project.

I would like to place the Wolverine body on this Little Tiger chassis, seen here. Then I have the sway bars, four-link bars, and rims to paint yellow; as well as a 540 CI Merlin engine to place in the truck. But how can I do so?
![Little Tiger (No Body)](https://user-images.githubusercontent.com/96151715/146093544-314b25cb-85de-4105-a06b-b226ca5561f1.jpg)

If anyone will help me with this project, please contact me on Discord. I wish to discuss this matter privately.

**Comment by paroj** [comment]
closing as unrelated to blender2ogre.

You should ask over at RoR:
https://github.com/RigsOfRods/rigs-of-rods

They even got tutorial for these sort of things:
https://docs.rigsofrods.org/tools-tutorials/blender-mesh-editing/

**Comment by KK-1701-K** [comment]
There is no one at that page to ask.

________________________________
