### ISSUE TITLE
Light Exports in Blender 3.0.0

### ISSUE THREAD

**Issue by jwitherell** [OGRECave/blender2ogre#133]
I think something with the light objects in blender changed from 2.x.x => 3.0.0.  When I exported a scene file, no light information was output.  If I changed scene.py in this way it started working again.  This is a clunky fix, but just wanted to share:

# in scene.py
Line 617: ob.type is now 'LIGHT' (rather than 'LAMP'
Lines 632 - 642: ob.data.use_diffuse (and use_specular) no longer seems to be a thing.  There is a ob.data.diffuse_factor and ob.data.specular_factor (scalar in the 0.0 to 1.0) range that ob.data.color can by multiplied by.

**Comment by sercero** [comment]
Thanks, thats something to look into.
