### ISSUE TITLE
Materials not displaying correctly after ogre export from blender

### ISSUE THREAD

**Issue by aeklant** [OGRECave/blender2ogre#137]
I have been running into issues when exporting models from blender into ogre. I specifically download the models using [mixamo](https://www.mixamo.com/#/) with the following procedure:

1. Select and download mixamo model (in .fbx format)
2. Import `.fbx` into blender
3. Export the model into ogre format using the blender2ogre addon

Note: I'm using `blender 2.83LTS`. 

The result looks consistent with the original FBX, the animations are preserved adequately and the .materials as well as the images that contain the textures seem correct to me, but the rendered model (in ogre-meshviewer) looks all black (no textures seem to be applied as expected).

Please note I am new to ogre and animation in general, so I understand I might be missing some important step or a simple solution. I just don't know what that could be at this point. 

So far I have tried:
- changing diffuse values in the .material file
- adding a `tex_coord_set 0` in all the texture units
- writing the absolute paths to all the textures

I have not noticed any of these changes having an effect. Any help appreciated.

This is what the model looks like in blender
![blender](https://user-images.githubusercontent.com/56091/166719151-705fab8e-5293-471a-b248-4ffd104daeeb.png)

And this is what it looks like in the ogre-meshviewer after the export
![ogre](https://user-images.githubusercontent.com/56091/166719164-807f8736-dca4-45d8-96dd-d8d86f75f2ce.png)

**Comment by paroj** [comment]
please attach your blend file here

**Comment by aeklant** [comment]
@paroj I am unable to attach the file here directly (I tried the .blend and also .zip). Please find it through [this link](https://drive.google.com/file/d/1HLpXvTJsIBcnHDqsHdq_wKpCDohATBYw/view?usp=sharing)

**Comment by paroj** [comment]
the exporter currently only handles diffuse and normal maps. The specular & glossiness maps are exported as additional diffuse layers, which modulate the colors to black. If you remove them the mesh should look mostly correct.

**Comment by paroj** [comment]
we should follow glTF and handle this case: https://docs.blender.org/manual/en/2.80/addons/io_scene_gltf2.html#metallic-and-roughness

**Comment by aeklant** [comment]
@paroj Thanks for the advise. I tried removing the glossiness and specular `.png` files and I do see a difference, but now the whole mesh looks golden-ish. See attached image
![Screenshot from 2022-05-05 12-08-25](https://user-images.githubusercontent.com/56091/166968056-5ef990d0-fe0b-4c5e-b08e-ab1032ac33f6.png)

I also tried going into the `.material` file and removing all the glossiness and specular texture units (as well as some diffuse ones that were duplicated) and it looks like a step in the right direction but not quite close yet. See image 
![Screenshot from 2022-05-05 12-10-04](https://user-images.githubusercontent.com/56091/166968450-513061a4-b1ca-4950-8493-0991a149ba78.png)

**Comment by aeklant** [comment]
[Here](https://drive.google.com/file/d/1TkDDeehC6YeS73U7adrVaAu83vYAlaQs/view?usp=sharing) are the blender2ogre output files, in case they can help diagnose the problem better.

**Comment by paroj** [comment]
with this one, the UV coordinates seem to be messed up and there are no tangents. Tangents are required to be able to use the normal-map.

I am not sure what messed up UV for you. Can you try using current master?

**Comment by paroj** [comment]
should be fixed by https://github.com/OGRECave/blender2ogre/commit/13a1d02e669ea02091aae10c5e033dd65c3f38d9

**Comment by aeklant** [comment]
@paroj I tried it with the current master (including [`13a1d02`](https://github.com/OGRECave/blender2ogre/commit/13a1d02e669ea02091aae10c5e033dd65c3f38d9)), and unfortunately it still looks like the last picture I shared (with the dark brown color in the cap and the shoes, and light brown everywhere else).

Could you share how or where you see that the UV coordinates are messed up and the tangents are missing? This way I can at least try to find the source of the problem.

**Comment by paroj** [comment]
ok, this is a Ogre bug: https://github.com/OGRECave/ogre/issues/2458

run OgreMeshUpgrader on the mesh to separate position & normals, then things work out even with skeletal animation.

**Comment by aeklant** [comment]
@paroj Thank you. I can confirm it works as expected now. I'll keep an eye on the ogre issue you opened.

Again, thanks for your help
