### ISSUE TITLE
Generating HLMS material json files

### ISSUE THREAD

**Issue by Phisketeer** [OGRECave/blender2ogre#148]
Hi guys,

I wonder if you plan to support the generation of the new material files in *.json format. Currently I am stuck in exporting objects from Blender to Ogre. The meshes are loading successfully but I am not able to get the materials imported to Ogre (blender2ogre generates still RTShader entries which are not enabled by the Ogre Next 2.3 branch by default). After almost one week trying now  I didn't find any converter from the old *.material to the new *material.json. Any ideas or suggestions how to perform this operation? (Also the migration page from Ogre 1.x to 2 is not available - the link does not work.) I simply want to use my 3D models from Blender in Ogre 2.3 without RTShader.

Thanks & best regards

**Comment by paroj** [comment]
there are currently no plans to do that

**Comment by jamieson** [comment]
Hey, I have started working on this for my own purposes over on my [fork](https://github.com/jamieson/blender2ogre/tree/topic/ogrev2materials). Posting here in case others find the current state useful and to avoid potentially duplicating efforts. Once I am satisfied I'll be filing a PR for review (of course!)

The branch has basic support for:
- [x] pbs datablocks
- [x] materials to separate files
- [x] materials to single file
- [x] convert texture images (ImageMagick)
- [x] diffuse
- [x] emissive
- [x] normalmap
- [x] metalness
- [x] roughness
- [x] specular
- [x] transparency
- [x] workflow

Several parameters to those blocks are simply set to Ogre Next's defaults or have arbitrary values I chose. These are noted by comments on the relevant line. Any input on correctness of decisions so far would be appreciated, especially as I am not primarily a graphics developer.

My current todo lists I am working through are below.

Validation of assumptions:
- [ ] `emissive.lightmap` is defaulted to false, looks like could map to `emission_strength_texture`. Would need to choose between `emissive_colour_texture` or using strength, what conditions?
- [ ] metalness appears to work on some test models, but not properly tested
- [ ] `roughness.value` in blender is 0-1, but Ogre is documented as 0-inf; needs scaling? Does it even have an effect if roughness_texture is set?
- [ ] `specular.value` (doc as colours) set by `material.specular_color` as bsdf doesn't have them, validate
- [ ] Transparency mode set by an arbitrary map, validate
- [ ] Transparency `use_alpha_from_textures` defaulted, is there a detectable case where it shouldn't be?

OgreNext pbs material features:
- [ ] blendblock
- [ ] macroblock
- [ ] shadow_const_bias
- [ ] recieve_shadows
- [ ] brdf
- [ ] detail_diffuse[]
- [ ] detail_normal[]
- [ ] detail_weight
- [ ] fresnel
- [ ] reflection
- [ ] two_sided
- [ ] `uv` always set to `0` on all blocks, identify uses for changing
- [ ] `sampler` always left unset to grab default, identify uses for changing

Quality and polish:
- [ ] implement timestamp checking to not copy images when not updated
- [ ] clean up module imports
- [ ] implement removal of temporary image files used during conversion
