### ISSUE TITLE
Missing template for new issues

### ISSUE THREAD

**Issue by sercero** [OGRECave/blender2ogre#168]
@paroj can you help me with this?

I was unable to find the option to create a template.

I would like to create one like the next comment (it's based on the OGRE one):

**Comment by sercero** [comment]
**System Information**
- Ogre Version: :grey_question: 
- Operating System / Platform: :grey_question: 
- Blender Version: :grey_question:

**Description of problem**


**blender2ogre.log**

```
paste your log here
```

**OgreXMLConverter.log** or **OgreMeshTool.log**

```
paste your log here
```

**Comment by paroj** [comment]
added

**Comment by sercero** [comment]
Thanks, just one thing I noticed in both templates (OGRE and here) is that it says "detailled".

Should say: "detailed". 😅
