### ISSUE TITLE
Shape key (pose) animation not exported

### ISSUE THREAD

**Issue by whatisor** [OGRECave/blender2ogre#17]
[shape-animation.blend.zip](https://github.com/OGRECave/blender2ogre/files/1477248/shape-animation.blend.zip)
I use test file from master branch, and added a shape key animation.
However, exporter does not export animation (only pose).

**Comment by VisualEntertainmentAndTechnologies** [comment]
One of my users is reporting the same issue with the exporter. Although he might not know exactly how to use it properly.

**Comment by paroj** [comment]
I did not try exporting animations with blender yet, therefore I can only point you to where the animations should be written:
https://github.com/OGRECave/blender2ogre/blob/master/io_ogre/ogre/mesh.py#L509

In case you want to dig into this issue: if you start blender in a console, you can see the output of your `print()` statements.

**Comment by RobJames-Texas** [comment]
I think I see the problem.  The shape_keys property is a collection. The length needs to be checked, loop over the collection and then you can export the key_blocks property.

I'm wondering if it was always a collection, or whether that is a recent change.  I will do some searching and see what I can find. It may require a conditional based on the version of blender being used.

**Comment by RobJames-Texas** [comment]
Ok, it was just how I was selecting it in the console. The code seems fine.  I applied a couple of shape keys, selected export, checked the box for "Shape Animation", and then press the export button. When I look at the XML, I see a "poses" section in the XML with the key I had added. When I load the exported mesh into "Ogre Meshy" I can switch between the poses with no issues.
