### ISSUE TITLE
FileNotFoundException: Cannot locate resource character.mesh in resource group OgreAutodetect.

### ISSUE THREAD

**Issue by vido89** [OGRECave/blender2ogre#179]
#### System Information
- Ogre Version: :OgreXMLConverte 0, 8, 3:
- Operating System / Platform: :Linux:
- Blender Version: :3.0:

#### Detailed description
When I export my character it does not show up in game and I can't open it
with ogre-meshviewer neather 

```
All done
Mesh: Loading character.mesh.
FileNotFoundException: Cannot locate resource character.mesh in resource group OgreAutodetect. in ResourceGroupManager::openResource at /build/ogre-meshviewer/parts/ogre/src/OgreMain/src/OgreResourceGroupManager.cpp (line 560)
```
#### OgreXMLConverter.log or OgreMeshTool.log

https://mega.nz/file/RcgW0DpZ#lgxzLhxZYWh4cqYngqj-ZBRV9hIu-j-2GUtSPUaMzbg

**Comment by sercero** [comment]
From the files you provided the .mesh was properly exported so the problem seems to be that the files are not in the correct place where the game is expecting them.

This is not an issue of `blender2ogre`
