### ISSUE TITLE
please consider adding a release

### ISSUE THREAD

**Issue by oaken-source** [OGRECave/blender2ogre#18]
this version of blender2ogre currently has no release and no version. please consider adding one.

Thank you :)

**Comment by paroj** [comment]
actually I did bump the version:
https://github.com/OGRECave/blender2ogre/blob/67875df294f772adab88455589d185bec1502bc4/io_ogre/__init__.py#L22

but yeah, an release would allow ease distribution & referencing.

**Comment by oaken-source** [comment]
this version number is inconsistent with the one in setup.py:
https://github.com/OGRECave/blender2ogre/blob/1fb73ac76b203f6d88f88b231366ab97b0bc33e1/setup.py#L8

**Comment by paroj** [comment]
https://github.com/OGRECave/blender2ogre/releases
