### ISSUE TITLE
Exporting Vertex or Morph Animations

### ISSUE THREAD

**Issue by blitzcoder** [OGRECave/blender2ogre#182]
Any documentation or quick guide on how to export as vertex or morph animation?

This [tool](https://forums.ogre3d.org/viewtopic.php?t=31683&start=50) seems to export MD2 animations, but repo is now 404.

**Comment by paroj** [comment]
https://bitbucket-archive.softwareheritage.org/new-static/2c/2cc29530-3ba0-4a50-a022-b799db3ef938/attachments/QuakeToOgre%20v2.1.zip

**Comment by blitzcoder** [comment]
Thanks @paroj and closing.
