### ISSUE TITLE
Got error (no skeleton) when export to OGRE in Blender

### ISSUE THREAD

**Issue by TranTriDat** [OGRECave/blender2ogre#188]
#### System Information
- Ogre Version: 13.6.5
- Operating System / Platform: Windows11
- Blender Version: 4.0

#### Detailed description
When I tried to export my pokemon model to OGRE, there is no skeleton file in the output folder. This is my setting on Blender 4.0:
![image](https://github.com/OGRECave/blender2ogre/assets/44765145/afedbc1f-6b10-4288-85cc-77f9a17ca48b)

#### blender2ogre.log
bpy.context.space_data.shading.type = 'MATERIAL'
bpy.data.window_managers["WinMan"].(null) = False
bpy.data.window_managers["WinMan"].(null) = False
bpy.data.window_managers["WinMan"].(null) = False
bpy.data.window_managers["WinMan"].(null) = False
Python: Traceback (most recent call last):
  File "E:\Blender4\4.0\scripts\addons\io_ogre\ui\export.py", line 210, in execute
    scene.dot_scene(target_path, target_file_name_no_ext)
  File "E:\Blender4\4.0\scripts\addons\io_ogre\ogre\scene.py", line 214, in dot_scene
    dot_scene_node_export(root, path = path, doc = doc,
  File "E:\Blender4\4.0\scripts\addons\io_ogre\ogre\scene.py", line 689, in dot_scene_node_export
    dot_scene_node_export( child,
  File "E:\Blender4\4.0\scripts\addons\io_ogre\ogre\scene.py", line 547, in dot_scene_node_export
    skeleton.dot_skeleton(ob, path, overwrite=overwrite, exported_armatures=exported_armatures)
  File "E:\Blender4\4.0\scripts\addons\io_ogre\ogre\skeleton.py", line 64, in dot_skeleton
    skel = Skeleton( obj )
  File "E:\Blender4\4.0\scripts\addons\io_ogre\ogre\skeleton.py", line 350, in __init__
    self.arm = arm = findArmature( ob )
  File "E:\Blender4\4.0\scripts\addons\io_ogre\ogre\skeleton.py", line 329, in findArmature
    if ob2.type == 'ARMATURE' and ob2.proxy == arm:
AttributeError: 'Object' object has no attribute 'proxy'
bpy.ops.ogre.export(filepath="E:\\Blender\\Pokemon Model\\Gen1\\Blend_model\\Eevee\\blender2ogre\\Eevee_render.scene", EX_SHARED_ARMATURE=False, EX_ONLY_KEYFRAMES=False, EX_ONLY_DEFORMABLE_BONES=False, EX_ONLY_KEYFRAMED_BONES=False)
Preferences saved
Python: Traceback (most recent call last):
  File "E:\Blender4\4.0\scripts\addons\io_ogre\ui\export.py", line 210, in execute
    scene.dot_scene(target_path, target_file_name_no_ext)
  File "E:\Blender4\4.0\scripts\addons\io_ogre\ogre\scene.py", line 214, in dot_scene
    dot_scene_node_export(root, path = path, doc = doc,
  File "E:\Blender4\4.0\scripts\addons\io_ogre\ogre\scene.py", line 689, in dot_scene_node_export
    dot_scene_node_export( child,
  File "E:\Blender4\4.0\scripts\addons\io_ogre\ogre\scene.py", line 547, in dot_scene_node_export
    skeleton.dot_skeleton(ob, path, overwrite=overwrite, exported_armatures=exported_armatures)
  File "E:\Blender4\4.0\scripts\addons\io_ogre\ogre\skeleton.py", line 64, in dot_skeleton
    skel = Skeleton( obj )
  File "E:\Blender4\4.0\scripts\addons\io_ogre\ogre\skeleton.py", line 350, in __init__
    self.arm = arm = findArmature( ob )
  File "E:\Blender4\4.0\scripts\addons\io_ogre\ogre\skeleton.py", line 329, in findArmature
    if ob2.type == 'ARMATURE' and ob2.proxy == arm:
AttributeError: 'Object' object has no attribute 'proxy'
bpy.ops.ogre.export(filepath="E:\\Blender\\Pokemon Model\\Gen1\\Blend_model\\Eevee\\blender2ogre\\Eevee_render.scene")

#### OgreXMLConverter.log or OgreMeshTool.log
00:13:14: XMLMeshSerializer reading mesh data from E:\Blender\Pokemon Model\Gen1\Blend_model\Eevee\blender2ogre\Eevee.mesh.xml...
00:13:14: Reading geometry...
00:13:14: Geometry done...
00:13:14: Reading submeshes...
00:13:14: Submeshes done.
00:13:14: Reading bone assignments...
00:13:14: Bone assignments done.
00:13:14: Reading mesh names...
00:13:14: Mesh names done.
00:13:14: XMLMeshSerializer import successful.
00:13:14: MeshSerializer writing mesh data to stream E:\Blender\Pokemon Model\Gen1\Blend_model\Eevee\blender2ogre\Eevee.mesh...
00:13:14: File header written.
00:13:14: Writing mesh data...
00:13:14: Writing submesh...
00:13:14: Exporting submesh texture aliases...
00:13:14: Submesh texture aliases exported.
00:13:14: Submesh exported.
00:13:14: Writing submesh...
00:13:14: Exporting submesh texture aliases...
00:13:14: Submesh texture aliases exported.
00:13:14: Submesh exported.
00:13:14: Writing submesh...
00:13:14: Exporting submesh texture aliases...
00:13:14: Submesh texture aliases exported.
00:13:14: Submesh exported.
00:13:14: Exporting skeleton link...
00:13:14: Skeleton link exported.
00:13:14: Exporting shared geometry bone assignments...
00:13:14: Shared geometry bone assignments exported.
00:13:14: Exporting bounds information....
00:13:14: Bounds information exported.
00:13:14: Exporting submesh name table...
00:13:14: Submesh name table exported.
00:13:14: Mesh data exported.
00:13:14: MeshSerializer export successful.

This is my blender file:
[Eevee_Blender.zip](https://github.com/OGRECave/blender2ogre/files/13655687/Eevee_Blender.zip)

4 images below is my selected options when exporting to OGRE:
![image](https://github.com/OGRECave/blender2ogre/assets/44765145/bf3e6dd6-c521-4b72-9866-e3e494f94272) 
![image](https://github.com/OGRECave/blender2ogre/assets/44765145/e3fb57d1-da5f-4a76-9405-d3fc2e7e7779)
![image](https://github.com/OGRECave/blender2ogre/assets/44765145/0211277e-e565-4c8c-9c67-d2ead32c63a8)
![image](https://github.com/OGRECave/blender2ogre/assets/44765145/0efd7eaf-ebcc-475b-a3df-9c8d06328589)

So I don't know what exactly wrong in my files and setting.

**Comment by paroj** [comment]
the exporter has not yet been updated for blender 4.0

**Comment by sercero** [comment]
Hmm, this happens also in Blender 3.6.8.

Might be a problem with the mesh...

**Comment by sercero** [comment]
@TranTriDat there is an actual bug in the code, but also your Armature has no actions and that is why the bug is triggered. As a workaround for now you can create a simple action and your skeleton will be exported

**Comment by TranTriDat** [comment]
Hi everyone, thank you for the feedback to solve this problem. 
I have changed to the older version of Blender and it works well now.
