### ISSUE TITLE
EdgeList generation broken with Ogre 14

### ISSUE THREAD

**Issue by paroj** [OGRECave/blender2ogre#235]
due to this change:
https://github.com/OGRECave/ogre/blob/master/Docs/14-Notes.md#meshupgrader

**Comment by sercero** [comment]
Well this is a problem since OgreMeshUpgrader does not tell us the version...

**Comment by sercero** [comment]
Nevermind, since the option is now called "-el" instead of "-e" it is possible to detect the version

**Comment by sercero** [comment]
Fixed by #236
