### ISSUE TITLE
Windows: Exporting using an older version of OgreXmlConverter will cause the export to hang

### ISSUE THREAD

**Issue by RobJames-Texas** [OGRECave/blender2ogre#24]
![ogreconverterparametererror](https://user-images.githubusercontent.com/1093532/40283566-e1ed40c8-5c45-11e8-9550-d67b45ff21d0.gif)

I'm using OgreXmlConverter 1.7.2 on Windows 10.

In util.py xml_converter_parameters() method, it calls the exe with "-v". This crashes the older versions of the converter.  The dialog box I added above will appear, and the export will not continue until it is closed.

I have fixed this locally by using the method found here:
https://stackoverflow.com/questions/5069224/handling-subprocess-crash-in-windows?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

**Comment by paroj** [comment]
alternatively, you can get an up-to-date version of OgreXmlConverter here
https://bintray.com/ogrecave/ogre/download_file?file_path=ogre-sdk-1.11.0-vc15-x64.zip

**Comment by RobJames-Texas** [comment]
I am using 1.7.2 because I am working on meshes for Torchlight 2 mods.
