### ISSUE TITLE
BoolProperties not saved when calling export operator

### ISSUE THREAD

**Issue by Boulouboup** [OGRECave/blender2ogre#245]
Hi, I'm writing my own addon in which I do several things and I use this one to export my objects to .mesh files. Instead of clicking on Files > Export > Ogre3D, I created a button that does it in one click for optimisation with the following operator: **bpy.ops.ogre.export('INVOKE_DEFAULT')**.

The problem is that some of the different options that I selected are not saved or remembered the next time I call the operator for exporting.

For example I deselected these 3 options:
![Capture](https://github.com/OGRECave/blender2ogre/assets/112648919/3fb72fc1-2eef-4c23-9f8c-a748c6b6a432)

The next time I call the export operator in my script they are not disabled:
![Capture2](https://github.com/OGRECave/blender2ogre/assets/112648919/ea5a5041-dcd0-4cee-b89e-ce08d4d30b8b)

However when I export this way: **Files > Export > Ogre3D**, (so by using its own addon) it does save and remember the selected options
![Capture3](https://github.com/OGRECave/blender2ogre/assets/112648919/8d5e4da1-124b-49a3-93f3-f847a202b406)

I'm new to Blender and Python, do you have any idea how to solve this problem?
Thanks in advance.

The addon:
![image](https://github.com/OGRECave/blender2ogre/assets/112648919/f3921f3c-bcdd-4566-ba72-ce5e479970bd)

**Comment by sercero** [comment]
Check out this document: https://github.com/OGRECave/blender2ogre/blob/master/Options.md

On how to export using the command line.

Also in the main README file it explains how to run blender2ogre from the command line.

**Comment by sercero** [comment]
> Ok thank you! So according to what I read (because there's no mention of it), I can't like open the file manager with the command line, select the options that I want then export? If I use the command line, I have to specify all the options in arguments?

Technically the options you specified should be remembered. 

So you should indicate in the command line the options that would be different from your saved ones.

In most cases that would be the filename.
