### ISSUE TITLE
Outdated Version

### ISSUE THREAD

**Issue by TYL9891** [OGRECave/blender2ogre#27]
i recently tried to install blender2ogre for blender 2.79b, i followed the steps, it did not work.

i then installed blender 2.75, and everything works

is this still getting attention? because it should.

i'd be grateful if the scripts were updated to work with the latest blender

and if it supported spline exporting to XML format for sonic generations

Thanks

**Comment by paroj** [comment]
works with 2.79b for me. Please provide an error message and used ogre/ OS + versions.

**Comment by paroj** [comment]
no reply from reporter
