### ISSUE TITLE
Constant value frame animation

### ISSUE THREAD

**Issue by alcasa04** [OGRECave/blender2ogre#31]
Mi problem is that Ogre seems to ignore constant value frames in animations.
In one of my animations, I need to do an object teleport to a near location. I have done the animation in blender using Graph Editor and making the translation constant, so it looks like It instantly changes position.
But when I export it to Ogre, I can still see the object (really fast) moving to one position to other. Is this any Ogre internal issue? Can I do it any other way? Some ideas?

**Comment by paroj** [comment]
please attach the exported files for further investigation

**Comment by paroj** [comment]
no response by reporter
