### ISSUE TITLE
Wrong output model scale and pose

### ISSUE THREAD

**Issue by he-lo-art** [OGRECave/blender2ogre#35]
Dear authors,
I have a complex scene and realized that an object's pose and scaling is not respected.
I could temporarily fix it for me by changing two statements in `io_ogre/ogre/mesh.py` in version 0.7.1:

`Line 225: x,y,z = swap(ob.matrix_world * v.co)`
`Line 563: x,y,z = swap( ob.matrix_world * pv.co - ob.matrix_world * v.co )`

Not sure whether that's the way to fix it. I hope it clarifies the issue.
Regards, Henning

**Comment by wxmerkt** [comment]
I came across the same issue - the above fix (now shifted by ~20 lines) helps to resolve it.

**Comment by paroj** [comment]
can one of you provide a pull-request?

**Comment by sercero** [comment]
This change is wrong!

What it does is apply the transform of the object to the Mesh.

With this change the scene export is not working properly (actually it makes the .scene redundant and the mesh objects displaced from their origin).

Please revert this change, and make it into an option.

I might do it when I have some time.

The option might be called something like "Bake object transforms into mesh".

@paroj, I summon you to get your opinion.

Thanks!
