### ISSUE TITLE
Compare with Kenshi exporter

### ISSUE THREAD

**Issue by paroj** [OGRECave/blender2ogre#36]
for general structure, blender 2.80 support:
https://www.lofigames.com/phpBB3/viewtopic.php?f=11&t=10732

**Comment by RobJames-Texas** [comment]
Hi there.  I have a fork from the original plugin by Dusho and I have added all the functionality updates from Kenshi plus a couple of things of my own while trying to make it all pep-8 compliant. My use case is specific to modding the game Torchlight, but I went through the kenshi plugin version by version so there is commit history consistent with what was in kenshi.
https://github.com/RobJames-Texas/torchlight-to-blender

**Comment by paroj** [comment]
fixed with  #109
