### ISSUE TITLE
'merge.' prefix not working in 2.8

### ISSUE THREAD

**Issue by bdotq** [OGRECave/blender2ogre#40]
So the 2.80 support branch has been usable, however I have come across the the 'merge.' prefix feature to merge grouped objects, failing quite fantastically.
Main issue is the change from Groups to Collections in 2.8 and how they are set up to behave I believe. So definitely some syntax updates, but also some other bugs I can't yet figure out

**Comment by bdotq** [comment]
Code is messy, but fixed: https://github.com/bdotq/blender2ogre/tree/2.80-support

**Comment by paroj** [comment]
can you provide a pull-request?

**Comment by paroj** [comment]
fixed in d79525c220ed55fb4ae69b411e1fd324143eb803
