### ISSUE TITLE
Custom normals broken by latest commit

### ISSUE THREAD

**Issue by SNiLD** [OGRECave/blender2ogre#45]
Custom normals broke from latest commit:
https://github.com/OGRECave/blender2ogre/commit/a73c84aa246f7b2d01a0e4e529c2972dacf4b0c8

Custom normals uses the `bm` but it is freed before it can be used.

**Comment by paroj** [comment]
fixed in 32c1e4eab3b7f8c86a5ab118981412d6a6e708b5
