### ISSUE TITLE
Mesh vertices get exported relative to scene origin

### ISSUE THREAD

**Issue by Fighter19** [OGRECave/blender2ogre#50]
When exporting with ```blender -b scene.blend --python ~/.config/blender/2.83/scripts/addons/io_ogre/console.py -- /tmp/blender 'scene abc' ```

The contained meshes get their vertices exported relative to the origin of the scene, as opposed to the origin of their mesh.
This makes adjusting them inside Ogitor really painful.

**Comment by paroj** [comment]
sounds like the transforms were applied to the vertices:
https://docs.blender.org/manual/en/latest/scene_layout/object/editing/apply.html

however, the plugin does not do this automatically..

**Comment by Fighter19** [comment]
I agree it sounds like that.
However when grabbing just one mesh and pasting it into a new blender file,
then resetting it by manually setting the Transform components to x,y,z=0,
the mesh is being exported as it should have been.

I'll try to create a simple blend file to reproduce this.

**Comment by Fighter19** [comment]
It's visible with the simple cube already.
Just export the cube and see how the position of the vertices are simply "1/-1".
Then move the cube using the G hotkey in object mode and export again,
The positions of the vertices are now changed.

**Comment by paroj** [comment]
I can confirm this. Also happens when using the preview.

However, I am not sure where the transform gets applied. If you want to take a look at it as well, the exporting happens here:
https://github.com/OGRECave/blender2ogre/blob/ddd756783bb47477f06bc15886a1c7e2154f7e16/io_ogre/ogre/mesh.py#L51-L61

**Comment by Fighter19** [comment]
I have found it here I think:
https://github.com/OGRECave/blender2ogre/blob/ddd756783bb47477f06bc15886a1c7e2154f7e16/io_ogre/ogre/mesh.py#L253
