### ISSUE TITLE
Wrong proportions

### ISSUE THREAD

**Issue by xander1401** [OGRECave/blender2ogre#68]
Hi,
I just managed to export files with your plugin.
However the objects are not scaled like defined in Blender.
It is always scaled down to 1x1x1 and not the wanted size.
Is this a known bug or is there a solution?

**Comment by paroj** [comment]
thats on purpose. scale is written to .scene instead of .mesh. See https://github.com/OGRECave/blender2ogre/issues/50

You can "apply" the scale in blender if you want it to be in .mesh.
