### ISSUE TITLE
An Ogre minimal loader

### ISSUE THREAD

**Issue by screwt** [OGRECave/blender2ogre#7]
Is there any minimal ogre3d project or interface or even class that is able to load the generated files ?
That would be usefull.

**Comment by paroj** [comment]
which files do you mean exactly? xml, mesh, material, dot?

**Comment by screwt** [comment]
Sorry it wasn't clear, i meant a set of cpp file + cmake that can be compiled. 
It would load scene generated files in an ogre3D render window.

**Comment by paroj** [comment]
should be probably rebased on OgreBites instead of BaseApplication and merged with: https://github.com/OGRECave/ogitor/tree/master/SceneLoader

**Comment by paroj** [comment]
the loader is on the way. Meanwhile you can use the dtd to validate the scene files:
https://github.com/OGRECave/DotSceneFormat

**Comment by paroj** [comment]
done https://github.com/OGRECave/DotSceneFormat
