### ISSUE TITLE
Add Mesh Version Convertion Capabilities

### ISSUE THREAD

**Issue by screwt** [OGRECave/blender2ogre#8]
As it is, the plugin do not offer the possibilty to convert the generated mesh to an other version.

In deed i was trying to load meshes to ogre2.1, i had to use the OgreMeshTool to convert from 1.10 to 2.1 to be able to load the mesh.

Targetting mesh output version would be usefull i think.

**Comment by OancaAndrei** [comment]
With #30 the add-on is now capable of exporting meshes to the new version. 
This works only if in your preferences `OGRETOOLS_XML_CONVERTER` points to a `OgreMeshTool` executable. 
Done that, in the export settings you'll be able to select which version to write (`v1` or `v2`).
Enjoy :)
